### ISSUE TITLE
Add "tabular" to tidy data bullet

### ISSUE THREAD

**Issue by AbbyBenson** [ESIPFed/bio-data-standards-primer#1]
Based on the work from creating the best practice companion document to the primer suggest adding "tabular" to the tidy data bullet such that it reads "Structure tabular data in tidy/long format".

**Comment by sformel-usgs** [comment]
Related to: https://github.com/ESIPFed/bds-primer-best-practices/issues/7

**Comment by AbbyBenson** [comment]
Done
