### ISSUE TITLE
Change "Record" to "Provide" for lat/lon bullet

### ISSUE THREAD

**Issue by AbbyBenson** [ESIPFed/bio-data-standards-primer#2]
Based on the work from creating the best practice companion document to the primer suggest changing "Provide" to "Record" for the lat/lon bullet such that it reads "Provide latitude and longitude in decimal degrees in WGS84"

**Comment by sformel-usgs** [comment]
Related to: https://github.com/ESIPFed/bds-primer-best-practices/issues/4

**Comment by AbbyBenson** [comment]
Done
