### ISSUE TITLE
Change globally unique to persistent for identifier bullet

### ISSUE THREAD

**Issue by AbbyBenson** [ESIPFed/bio-data-standards-primer#3]
Based on the work from creating the best practice companion document to the primer suggest changing "globally unique" to "persistent" for the identifier bullet such that it reads "Use persistent identifiers"

**Comment by sformel-usgs** [comment]
https://github.com/ESIPFed/bds-primer-best-practices/issues/8

**Comment by AbbyBenson** [comment]
Done
